### ISSUE TITLE
where is default reservation reminder "15 minutes" defined?

### ISSUE THREAD

**Issue by guilegatan** [LibreBooking/app#294]
If reminders are enabled in config, one can activate a reminder for every reservation. However, the default preset is "15 minutes".

If I change "default.start.reminder" to my preference "24 hours" in "config.php", the reminder checkbox is by default enabled when creating a new reservation. If I do not set the "default.start.reminder" variable, the checkbox is disabled, but the preset is "15 minutes".

I want to achive a situation, where the checkbox is disabled by default, but the preset is "24 hours". In this case our users only have to tick the box, and don't bother with the reminder time.

Thank you!

![Zwischenablage01](https://github.com/LibreBooking/app/assets/16672201/585b4ed1-b2b9-4087-a965-2dd9aa4d3974)

**Comment by treborin** [comment]
Hi @guilegatan ,

> I want to achive a situation, where the checkbox is disabled by default, but the preset is "24 hours". In this case our users only have to tick the box, and don't bother with the reminder time.

You must edit template file tpl/Reservation/create.tpl 
First, about line 290, change input value to 25:

![image](https://github.com/LibreBooking/app/assets/31905622/7d73d619-9d01-454b-931d-cf1606f29a88)

Second, move Hours option to the top of the 3 select options availables (Minutes, Hours, Days) in order to view it selected first:

![image](https://github.com/LibreBooking/app/assets/31905622/2ffd8795-2434-43e9-843a-376264bd1597)

Do not set the "default.start.reminder" variable in config.php

Hope this helps,

**Comment by guilegatan** [comment]
Thank you very much for the info! I also had to flush the template cache directory "tpl_c" to get it to work correctly.
Its working exactly as intended.
