### ISSUE TITLE
Availability for a device can be seen for 1 week in the future "/Web/Services/index.php/Resources/Availability"

### ISSUE THREAD

**Issue by powerscooter** [LibreBooking/app#376]
Hello everyone,
I have started to use LibreBooking for the first time. I have already written myself some functions to interact with Librebooking's API.
I noticed that when I query the availability of my resources, I only see the availability of a resource for 1 week in the future.

So where can I configure it to show me the availability for the future, e.g. the next year?

I currently have the following fields displayed:
{'available': True, 'availableAt': None, 'availableUntil': '2024-06-27T08:00:00+0200'}, {'name': 'scratchy'}

I see that the value "availibeUntil" is always only for exactly 1 week in the future. 

If I now reserve the device on 10 August, for example, I would like to see that the device is only available until 10 August.

API Endpoint: "/Web/Services/index.php/Resources/Availability"

Thanks in advance

**Comment by JohnVillalovos** [comment]
I don't have an answer for you. But I will just comment that the API has a lot of "issues". So don't be surprised if things don't work as you expect.

I have been working on fixing things as I discover them. So the API is better than it was a year ago, but there is more to do.

If you want to figure out the code that would be great. If you figure out there is a bug, then a PR to fix that bug is great. The maintainer has been pretty responsive on getting things merged in. Usually within a week of the PR being posted.

**Comment by JohnVillalovos** [comment]
The API documentation for that endpoint says that you can provide `availableAt` and `availableUntil`. Maybe that would work?

From docs on https://YOUR_SYSTEM_NAME_HERE/Web/Services/#Resources

Returns resource availability for the requested resource (optional). "availableAt" and "availableUntil" will include availability through the next 7 days
