### ISSUE TITLE
Limit languages for emails

### ISSUE THREAD

**Issue by hakito** [LibreBooking/app#416]
When extending the templates with additional information, it is difficult or impossible for my client to update all translations.

We came up with the idea to restrict the languages to a certain set at least for the email templates. Users with a language setting that is not within the set, will fall back to the default translation.

I will come up with a PR soon to address this issue.

**Comment by lucs7** [comment]
Unfortunately, this commit seems to break the resource view causing:

PHP Fatal error:  Access level to ResourceStatusChangeEmail::$email must be protected (as in class EmailMessage) or weaker in /var/www/html/lib/Email/Messages/ResourceStatusChangeEmail.php on line 5

I tried to backtrack where the current development branch breaks, and in the previous commit, it did not occur.
It seems to be caused by the change from private to protected for the $email in EmailMessage.php

I guess the Email/Messages would have to be adjusted to the same visibility, but I am not really into php to be of help here

**Comment by hakito** [comment]
@lucs7 I created a new PR that addresses the issue and renames the private fields of the derived classes.
